# Generated by Django 4.1.3 on 2022-12-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frikis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tusnoticias',
            name='titulo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
