# Generated by Django 4.1.7 on 2023-04-06 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frikis', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tusnoticias',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
