# Generated by Django 4.1.7 on 2023-04-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frikis', '0006_tusnoticias_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tusnoticias',
            name='noticia_text',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='tusnoticias',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
